"""
Generated by 'esmerald createapp' using Esmerald 2.4.0.
"""
from typing import List

from products.models import Product

from esmerald import APIView, get


class ProductView(APIView):
    path: str = "/products"

    @get("/")
    async def get_all_products(self) -> List[Product]:
        """Gets all products with corresponding users"""
        return await Product.query.all()
