version: "3.8"
services:
  db:
    restart: always
    image: postgres:12.3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "kokoserver"
    expose:
      - "5432"
    volumes:
      - "kokoserver:/var/lib/postgresql/data"
      # - ./create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
    command: >-
        --jit=false
    ports:
      - "5432:5432"

volumes:
  kokoserver:
    external: true
