"""
Esmerald settings for kokoserver project.

Generated by 'esmerald createproject' using Esmerald 2.4.0.
"""

import os
from functools import cached_property
from typing import Optional, Tuple

from edgy import Database, Registry
from esmerald.conf.enums import EnvironmentType
from esmerald.conf.global_settings import EsmeraldAPISettings


class DatabaseSettings(EsmeraldAPISettings):
    """
    Settings responsible for the database connection.

    postgresql+asyncpg://postgres:postgres@localhost:5432/edgy"
    """

    db_user: str = os.environ.get("DB_USER", "postgres")
    db_password: str = os.environ.get("DB_PASS", "postgres")
    db_host: str = os.environ.get("DB_HOST", "localhost")
    db_port: int = os.environ.get("DB_PORT", 5432)
    db_name: str = os.environ.get("DB_NAME", "kokoserver")

    @cached_property
    def db_registry(self) -> Tuple[Registry, Database]:
        """
        Returns the registry settings.
        """
        connection_string: str = f"postgresql+asyncpg://{self.db_user}:{self.db_password}@{self.db_host}:{self.db_port}/{self.db_name}"
        database: Database = Database(connection_string)
        return Registry(database=database), database


class AppSettings(DatabaseSettings):
    app_name: str = "My application in production mode."
    title: str = "My kokoserver"
    environment: Optional[str] = EnvironmentType.PRODUCTION
    secret_key: str = (
        "esmerald-insecure-g#&amp;kx6cp01ft*sugodzx5bjkhv&amp;3r5$8x&amp;f_5)=2c3a39b8*6+"
    )
